Fix password reset edit form
phoenixframework/phoenix pull request #5131
Opened 2022-11-27 03:45 UTC by joseph-lozano

the reset_password edit form did not have password or password_confirmation inputs.

2022-11-27 04:02 UTC, joseph-lozano commented
Happy to add assertions that these inputs exist, but I also am not sure they are necessary.

2022-12-29 01:31 UTC, bemesa21 requested changes
Good catch! those inputs were definitely needed.

I suggested a few changes just to keep the template the same as the one generated with the --live option.

2022-12-29 01:31 UTC, bemesa21 commented on priv/templates/phx.gen.auth/reset_password_edit.html.heex
> +    <.input field={{f, :password}} type="password" placeholder="Password" required />
```suggestion
    <.input field={{f, :password}} type="password" label="New Password" required />
```

2022-12-29 01:31 UTC, bemesa21 commented on priv/templates/phx.gen.auth/reset_password_edit.html.heex
> +    <.input field={{f, :password_confirmation}} type="password" placeholder="Password Confirmation" required />
```suggestion
    <.input field={{f, :password_confirmation}} type="password" label="Confirm new password" required />
```

2022-12-29 01:31 UTC, bemesa21 commented on priv/templates/phx.gen.auth/reset_password_edit.html.heex
> +    <:subtitle>Use the form below to reset your password</:subtitle>
```suggestion
```

2022-12-29 01:31 UTC, bemesa21 commented on priv/templates/phx.gen.auth/reset_password_edit.html.heex
> +    Password Reset
Reset password

2022-12-29 01:33 UTC, bemesa21 requested changes

2022-12-29 01:33 UTC, bemesa21 commented on priv/templates/phx.gen.auth/reset_password_edit.html.heex
> +    Password Reset
```suggestion
    Reset Password
```

2023-01-04 19:30 UTC, merged

2023-01-04 19:36 UTC, bemesa21 commented
✨✨✨💫